### ISSUE TITLE
Doesn't seem to be working for me

### ISSUE THREAD

**Issue by Gacnt** [artificialio/sails-hook-babel#4]
Hi,

I did `npm install sails-hook-babel` all went well and it installed,

then I go and make

`assets/js/main.js`

Then to test it out I ran:
```
(() =>
  console.log('Hi')
)();
```

But I just get an error. It compiles just fine on the babel website so I'm not sure what I'm doing wrong.

**Comment by mattcodez** [comment]
This hook is only for server side code.

**Comment by Gacnt** [comment]
@mattcodez thanks

**Comment by Merri** [comment]
I wonder if someone could fix the sentence "Sails JS hook to activate ES6/7 Javascript code for your whole sails app, via https://babeljs.io/." so that the term **server side** is included? At least I understand "whole sails app" to include client side code. At the moment I feel like I've now spent way too much time on wondering why a thing doesn't work simply by misunderstanding what a tool was for.

**Comment by Gacnt** [comment]
I agree, whole says app is incredibly misleading

**Comment by jodyheavener** [comment]
I also came across this issue thinking it was meant for client side. I wasn't too difficult to add, though. Not sure if this is the best place for them, but are some instructions:

1. Install Grunt Babel `npm install --save grunt-babel`
2. Create a `babel.js` file under `tasks/config` and add something like the following:

  ```
  module.exports = function(grunt) {

      grunt.config.set('babel', {
        dev: {
          files: [{
            expand: true,
            cwd: 'assets/js/',
            src: ['**/*.js', '!dependencies/**/*.js'],
            dest: '.tmp/public/js/',
            ext: '.js'
          }]
        }
      });

      grunt.loadNpmTasks('grunt-babel');
  };
  ```
  It's up to you, but I'm not touching the dependencies folder.
  
3. Since Babel copies the JS over, update the `copy:dev` tasks's `src` to exclude `js` (`copy.js` under `tasks/config`). It should looks something like this:
  
  ```
  src: ['**/*.!(coffee|less|js)'],
  ```

4. Update both `compileAssets.js` and `syncAssets.js` under `tasks/config` to include the Babel dev task: `'babel:dev'`

That _should_ do it. Try running `sails lift --verbose` to see if Babel is running, and then try writing some fancy ES6 to try it out! If I'm missing something please ping me.

**Comment by mattcodez** [comment]
@jodyheavener Thanks for writing up the client side implementation. If I had to add anything, I personally don't feel an ES6 implementation is complete without support for modules. Unfortunately, the transpilers don't do this by themselves. I've managed to do it with Sails, Babel and Browserify. I did this a while ago, but I think you can just add grunt-browserify and the following browserify.js in `tasks/config`.
```
module.exports = function(grunt) {

  grunt.config.set('browserifyBundleName', 'bundle.js');
  grunt.config.set('browserify',{
    dev: {
      files: {
        '.tmp/public/js/<%= browserifyBundleName %>':
          ['.tmp/public/js/*.js'],
      },
      options: {
        transform: ['babelify']
      }
    },
    dist:{

    }
  });

  grunt.loadNpmTasks('grunt-browserify');
};
```

**Comment by athlite** [comment]
I tried to do this with jspm + systemjs and it worked pretty well @mattcodez. The strain when transpiling realtime after file changes can high though. For building with jspm in sails try this:
```
module.exports = function(grunt) {
	grunt.config.set('jspm', {
		dev: {
			files: {
				src: "app/main",
				dst: "assets/js/dependencies/build.all.js"
			}
		},
		commands: {
			build: "jspm bundle-sfx <%= jspm.dev.files.src %> <%= jspm.dev.files.dst %>"
		}
	});	
	grunt.registerTask('jspm:build', "Build jspm bundle", function() {
		var childProcess,src,dst,done, jspm = require('jspm');
		src = grunt.config.get('jspm').dev.files.src;
		dst = grunt.config.get('jspm').dev.files.dst;
		done = grunt.task.current.async();
		jspm.bundleSFX(src, dst).then(function() {
			done("ok");
		});
	});
};
```

**Comment by mattcodez** [comment]
Thanks for this @athlite I hadn't used JSPM before so it took me a bit to figure it out. For anyone else reading, here's what I did. (Note, this is in a working state but may not be perfect, haven't tested with production deployment either).

Not in exact order
* Globally install jspm `npm install jspm -g`
* Locally install jspm `npm install jspm --save` //Should this be --save-dev ?
* Run `jspm init` and just use default settings
* Add contents from post by @athlite to `tasks/register/jspm.js`
* Create new folder `./app`
* Create new file `app/main.js`
* Add 'jspm:build' after 'jst:dev' in `tasks/register/compileAssets.js` and `syncAssets.js`
* Add `'app/**'` after `pipeline.js` in `files` array in `tasks/config/watch.js`

Should be all you need. Might need to re-lift sails after the task has run once so that Sails adds `build.all.js` to your `layout.ejs` file.

**Comment by mattcodez** [comment]
Also, errors are suppressed with the above code, simple modification:
```
jspm.bundleSFX(src, dst).then(function() {
            done("ok");
        })
        .catch(function(err){
          console.error(err.stack);
        });
```

**Comment by athlite** [comment]
I'm optimistic about jspm @mattcodez . As you said, modules, the ES6 way, is a big frikkin deal, and the way to go imho. The other alternatives lingering about just dont feel right. And at the bottom line; why oh why is nodejs still using require? It's like PHP!
